#ifndef CONFIG_EXAMPLE_H
#define CONFIG_EXAMPLE_H

#define WIFI_SSID "YOUR_WIFI_NAME"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

#define SERVER_IP "192.168.1.100"
#define SERVER_PORT 8000

#define DEVICE_ID "tracker_01"

#endif